# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WifiPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifiName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('loc_long', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
