# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifipoint',
            name='dest_to_orig',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
